# Generated by Django 5.0.6 on 2024-06-30 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ariticles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(max_length=400)),
                ("price", models.DecimalField(decimal_places=2, max_digits=100)),
                ("actif", models.BooleanField(default=False)),
                ("image", models.ImageField(blank=True, upload_to="images/")),
                ("slug", models.SlugField(max_length=10)),
            ],
            options={
                "verbose_name": "Article",
                "verbose_name_plural": "Ariticles",
            },
        ),
    ]
